# Generated by Django 4.2.11 on 2024-06-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_orderitem_user_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
