# Generated by Django 4.2.11 on 2024-06-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_order_eat_alter_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='eat',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('take_out', 'Take Out'), ('on_the_spot', 'On The Spot')], default='delivery', max_length=20),
        ),
    ]
