# Generated by Django 4.2.11 on 2024-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_order_eat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='eat',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Take Out', 'Take Out'), ('On The Spot', 'On The Spot')], default='Delivery', max_length=20),
        ),
    ]
