# Generated by Django 4.2.11 on 2024-06-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_ratingstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='delivery.store'),
        ),
    ]
