# Generated by Django 4.2.11 on 2024-06-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_likestore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeStore',
        ),
    ]
