# Generated by Django 4.2.11 on 2024-06-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_delete_likestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySuppliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(related_name='suppliments', to='delivery.categorysuppliment')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='suppliments',
            field=models.ManyToManyField(related_name='items', to='delivery.suppliment'),
        ),
    ]
