# Generated by Django 4.2.11 on 2024-06-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_remove_suppliment_category_delete_categorysuppliment'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliment',
            name='category',
            field=models.CharField(choices=[('Suppliment', 'Suppliment'), ('Boisson', 'Boisson')], default='Suppliment', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In Progress', 'In Progress'), ('In Transit', 'In Transit'), ('Complete', 'Complete')], default='Received', max_length=20),
        ),
    ]
