# Generated by Django 4.2.11 on 2024-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_suppliment_category_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
