# Generated by Django 4.2.11 on 2024-06-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_suppliment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='personalized',
            field=models.BooleanField(default=False),
        ),
    ]
