# Generated by Django 4.2.11 on 2024-06-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_orderitem_suppliments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='suppliments',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='suppliments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
