# Generated by Django 4.2.11 on 2024-06-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_orderitem_suppliments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='suppliments',
        ),
    ]
