# Generated by Django 4.2.11 on 2024-06-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_orderitem_suppliments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
