# Generated by Django 4.2.11 on 2024-06-07 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0028_souscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='souscategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.souscategory'),
        ),
    ]
