# Generated by Django 4.2.11 on 2024-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0031_subcategory_item_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(choices=[('kasserine', 'Kasserine'), ('tunis', 'Tunis'), ('sousse', 'Sousse')], default='kasserine', max_length=20),
        ),
    ]
