# Generated by Django 4.2.11 on 2024-06-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0036_store_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='password',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
