# Generated by Django 4.2.11 on 2024-06-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0038_customerdeliveryform'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStoreForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
