# Generated by Django 4.2.11 on 2024-06-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_remove_orderitem_suppliments'),
        ('accounts', '0004_remove_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adress',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_stores',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='delivery.store'),
        ),
    ]
